#!/usr/bin/env bash
#INstall NGINX and configue the default html page
# installs nginx and configures it on a remote server

sudo apt-get update -y
sudo apt-get install nginx -y
sudo service nginx start
sudo chmod 644 /var/www/html/index.nginx-debian.html
echo "Hello World!" > /var/www/html/index.nginx-debian.html
sudo service nginx restart
apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo hello world > /tmp/test
printf %s "server {
    listen		80 default_server;
    listen		[::]:80 default_server;
    root		/var/www/html;
    index		index.html index.htm index.nginx-debian.html;
}"
> /etc/nginx/sites-available/default

service nginx start
