#!/usr/bin/env bash
# Installs Nginx
#INstall NGINX and configue the default html page

sudo apt-get update -y
sudo apt-get install nginx -y
sudo service nginx start
sudo chmod 644 /var/www/html/index.nginx-debian.html
echo "Holberton School" > /var/www/html/index.nginx-debian.html
echo "Hello World!" > /var/www/html/index.nginx-debian.html
sudo service nginx restart
