#!/usr/bin/env bash
# Configuring a server with specification XYZ

sudo apt update
sudo apt install nginx -y
sudo ufw allow 22
sudo ufw allow 80
sudo ufw --force enable
echo hello world > /tmp/test
sed -i 's/80/8080/g' /etc/nginx/sites-enabled/default
sudo service nginx restart
